"""O/F- and pressure-dependent N2O/HTPB combustion properties.

Replaces the single set of prescribed constants used in Milestones 3 and 4 with a
frozen NASA CEA equilibrium table, interpolated at runtime.

Provenance
----------
The table in ``data/n2o_htpb_equilibrium.csv`` is generated by
``scripts/generate_thermochemistry_table.py`` using **NASA CEA** through the
``rocketcea`` wrapper (Gordon & McBride, NASA RP-1311).  The generator is a
build-time tool: this module reads only the committed CSV, so a normal install
has no CEA dependency and runtime results cannot drift with a solver version.

Reactants, taken verbatim from CEA's own cards::

    fuel R-45(HTPB FROM_RPL_DATA) C 7.3165 H 10.3360 O 0.1063  h,cal=1200  t=298.15 K
    oxid NitrousOxide N 2.0 O 1.0                              h,cal=19467 t=298.15 K

HTPB is therefore a **surrogate composition**, not a unique molecule: real HTPB
varies with formulation, cure system and additives, none of which are modelled.

Combustion efficiency convention
--------------------------------
The table stores the **ideal** equilibrium ``c*``.  The Milestone 3 architecture
is preserved unchanged: a combustion efficiency multiplies it to give the
delivered value.

    c*_delivered = eta_c* x c*_ideal(O/F, p_c)

The efficiency is applied **exactly once**, here, and the stored column is ideal.
``tests/test_thermochemistry.py`` asserts the table is not itself de-rated, so the
loss cannot be double counted.

Effective molar mass
--------------------
At the fuel-rich mixture ratios this motor runs at, CEA predicts condensed carbon
in the chamber and reports two molecular weights.  This module carries CEA's
``M, (1/n)`` -- the mass of the *whole* mixture per mole of gas -- because that is
the one which reproduces CEA's own sound speed and which a single-species nozzle
model needs.  The gas-phase value is kept only as a diagnostic; their ratio flags
where a condensed phase is present.

The specific gas constant is recomputed from the interpolated molar mass rather
than interpolated itself, so ``R = R_u / M`` holds exactly at every query point
rather than only at grid nodes.

Units
-----
SI throughout: Pa, K, m/s, kg/mol, J/(kg K).
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass
from enum import Enum
from functools import lru_cache
from pathlib import Path

import numpy as np

__all__ = [
    "DEFAULT_C_STAR_EFFICIENCY",
    "DEFAULT_TABLE_PATH",
    "GRID_RELATIVE_TOLERANCE",
    "TableStatus",
    "ThermochemicalState",
    "ThermochemistryTable",
    "default_table",
]

#: Location of the committed CEA table.
DEFAULT_TABLE_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / ("n2o_htpb_equilibrium.csv")
)

#: Combustion efficiency applied to the ideal ``c*``.  Identical to the value
#: Milestone 3 prescribed -- the midpoint of the 94-98 % measured by Rezaei,
#: Soltani & Mohammadi (2018) for HTPB/N2O -- so the two milestones remain
#: directly comparable.
DEFAULT_C_STAR_EFFICIENCY = 0.96

#: Relative slack allowed at the grid edges, to absorb floating-point round-off in
#: a query that is mathematically on the boundary.  Roughly 1e-9 of the grid span;
#: far too small to hide a genuine excursion.
GRID_RELATIVE_TOLERANCE = 1.0e-9

_UNIVERSAL_GAS_CONSTANT_J_MOL_K = 8.314462618

_FIELDS = (
    "ideal_cstar_m_s",
    "gamma",
    "chamber_temperature_k",
    "effective_molar_mass_kg_mol",
    "gas_molar_mass_kg_mol",
)


class TableStatus(Enum):
    """Where a query sits relative to the tabulated domain."""

    WITHIN_TABLE = "WITHIN_TABLE"
    O_F_BELOW_TABLE = "O_F_BELOW_TABLE"
    O_F_ABOVE_TABLE = "O_F_ABOVE_TABLE"
    PRESSURE_BELOW_TABLE = "PRESSURE_BELOW_TABLE"
    PRESSURE_ABOVE_TABLE = "PRESSURE_ABOVE_TABLE"


@dataclass(frozen=True)
class ThermochemicalState:
    """Interpolated combustion properties at one ``(O/F, p_c)`` point."""

    of_ratio: float
    chamber_pressure_pa: float
    ideal_c_star_m_s: float
    c_star_efficiency: float
    c_star_m_s: float
    gamma: float
    chamber_temperature_k: float
    effective_molar_mass_kg_mol: float
    gas_molar_mass_kg_mol: float
    specific_gas_constant_j_kg_k: float
    status: TableStatus

    @property
    def is_within_table(self) -> bool:
        return self.status is TableStatus.WITHIN_TABLE

    @property
    def condensed_phase_mass_ratio(self) -> float:
        """``M_eff / MW_gas`` [-].

        Exactly 1 when every product is gaseous; greater than 1 when CEA places
        some of the mass in a condensed phase, since that mass then contributes to
        the mixture without contributing moles of gas.
        """
        return self.effective_molar_mass_kg_mol / self.gas_molar_mass_kg_mol

    @property
    def has_condensed_phase(self) -> bool:
        """True where equilibrium puts carbon (soot) into the chamber."""
        return self.condensed_phase_mass_ratio > 1.0 + 1.0e-6


def _check_finite_positive(name: str, value: float) -> float:
    v = float(value)
    if not math.isfinite(v):
        raise ValueError(f"{name} must be finite, got {value!r}")
    if v <= 0.0:
        raise ValueError(f"{name} must be strictly positive, got {v!r}")
    return v


@dataclass(frozen=True)
class ThermochemistryTable:
    """A frozen, bilinearly interpolated CEA equilibrium table."""

    of_values: np.ndarray
    pressure_values: np.ndarray
    fields: dict[str, np.ndarray]
    source: str

    @classmethod
    def from_csv(cls, path: Path | str = DEFAULT_TABLE_PATH) -> ThermochemistryTable:
        """Load a table, ignoring ``#`` provenance lines."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(
                f"the thermochemistry table was not found at {path}.\n"
                "It is committed to the repository at data/n2o_htpb_equilibrium.csv and is "
                "located relative to the installed package, so this normally means the package "
                'was installed non-editably. Install it with `pip install -e "."` from a clone, '
                "or pass an explicit path to from_csv(). Regenerating the table instead needs "
                'the optional CEA extra: `pip install -e ".[cea]"` then '
                "`python scripts/generate_thermochemistry_table.py`."
            )
        with path.open(encoding="utf-8") as handle:
            rows = list(csv.DictReader([line for line in handle if not line.startswith("#")]))
        if not rows:
            raise ValueError(f"no data rows found in {path}")

        of_values = np.array(sorted({float(row["of"]) for row in rows}), dtype=float)
        pressure_values = np.array(
            sorted({float(row["chamber_pressure_pa"]) for row in rows}), dtype=float
        )
        if of_values.size < 2 or pressure_values.size < 2:
            raise ValueError("the table needs at least two values on each axis")
        if not np.all(np.diff(of_values) > 0.0):
            raise ValueError("the O/F grid must be strictly increasing")
        if not np.all(np.diff(pressure_values) > 0.0):
            raise ValueError("the chamber-pressure grid must be strictly increasing")
        if len(rows) != of_values.size * pressure_values.size:
            raise ValueError(
                f"the table is not a complete rectangular grid: {len(rows)} rows for "
                f"{of_values.size} x {pressure_values.size} nodes"
            )

        fields = {
            name: np.full((of_values.size, pressure_values.size), np.nan, dtype=float)
            for name in _FIELDS
        }
        for row in rows:
            i = int(np.searchsorted(of_values, float(row["of"])))
            j = int(np.searchsorted(pressure_values, float(row["chamber_pressure_pa"])))
            for name in _FIELDS:
                fields[name][i, j] = float(row[name])
        for name, grid in fields.items():
            if np.any(~np.isfinite(grid)):
                raise ValueError(f"the table has missing or non-finite entries in {name!r}")
        return cls(
            of_values=of_values,
            pressure_values=pressure_values,
            fields=fields,
            source=str(path),
        )

    # -- domain -----------------------------------------------------------

    @property
    def of_bounds(self) -> tuple[float, float]:
        return float(self.of_values[0]), float(self.of_values[-1])

    @property
    def pressure_bounds_pa(self) -> tuple[float, float]:
        return float(self.pressure_values[0]), float(self.pressure_values[-1])

    def status(self, of_ratio: float, chamber_pressure_pa: float) -> TableStatus:
        """Classify a query without evaluating it."""
        of = float(of_ratio)
        pressure = float(chamber_pressure_pa)
        if not math.isfinite(of) or not math.isfinite(pressure):
            raise ValueError("of_ratio and chamber_pressure_pa must be finite")
        of_low, of_high = self.of_bounds
        p_low, p_high = self.pressure_bounds_pa
        of_slack = GRID_RELATIVE_TOLERANCE * (of_high - of_low)
        p_slack = GRID_RELATIVE_TOLERANCE * (p_high - p_low)
        if of < of_low - of_slack:
            return TableStatus.O_F_BELOW_TABLE
        if of > of_high + of_slack:
            return TableStatus.O_F_ABOVE_TABLE
        if pressure < p_low - p_slack:
            return TableStatus.PRESSURE_BELOW_TABLE
        if pressure > p_high + p_slack:
            return TableStatus.PRESSURE_ABOVE_TABLE
        return TableStatus.WITHIN_TABLE

    # -- interpolation ----------------------------------------------------

    def _bilinear(self, grid: np.ndarray, of: float, pressure: float) -> float:
        """Plain bilinear interpolation.

        Deliberately not a spline: a high-order interpolant can overshoot, and the
        gamma surface has a genuine near-discontinuity where the chamber soot
        boundary is crossed.  Bilinear cannot invent values outside the local node
        range, which matters far more here than smoothness.
        """
        of_values, pressure_values = self.of_values, self.pressure_values
        i = int(np.clip(np.searchsorted(of_values, of) - 1, 0, of_values.size - 2))
        j = int(
            np.clip(np.searchsorted(pressure_values, pressure) - 1, 0, pressure_values.size - 2)
        )
        of_lo, of_hi = of_values[i], of_values[i + 1]
        p_lo, p_hi = pressure_values[j], pressure_values[j + 1]
        u = 0.0 if of_hi == of_lo else (of - of_lo) / (of_hi - of_lo)
        v = 0.0 if p_hi == p_lo else (pressure - p_lo) / (p_hi - p_lo)
        u = min(max(u, 0.0), 1.0)
        v = min(max(v, 0.0), 1.0)
        return float(
            grid[i, j] * (1.0 - u) * (1.0 - v)
            + grid[i + 1, j] * u * (1.0 - v)
            + grid[i, j + 1] * (1.0 - u) * v
            + grid[i + 1, j + 1] * u * v
        )

    def evaluate(
        self,
        of_ratio: float,
        chamber_pressure_pa: float,
        *,
        c_star_efficiency: float = DEFAULT_C_STAR_EFFICIENCY,
    ) -> ThermochemicalState:
        """Interpolate the combustion properties at one operating point.

        Raises :class:`ValueError` outside the tabulated domain.  Extrapolating an
        equilibrium table is not a small approximation -- the property surfaces
        change character at the soot boundary and near the c* peak -- so the
        deliberate behaviour is to refuse, and let the caller terminate a run.
        """
        of = _check_finite_positive("of_ratio", of_ratio)
        pressure = _check_finite_positive("chamber_pressure_pa", chamber_pressure_pa)
        efficiency = float(c_star_efficiency)
        if not math.isfinite(efficiency) or not (0.0 < efficiency <= 1.0):
            raise ValueError(f"c_star_efficiency must lie in (0, 1], got {c_star_efficiency!r}")

        status = self.status(of, pressure)
        if status is not TableStatus.WITHIN_TABLE:
            of_low, of_high = self.of_bounds
            p_low, p_high = self.pressure_bounds_pa
            raise ValueError(
                f"query outside the thermochemistry table ({status.value}): "
                f"O/F {of!r}, p_c {pressure!r} Pa; the table covers "
                f"O/F {of_low}-{of_high} and {p_low}-{p_high} Pa. "
                "Extrapolation is refused by design."
            )

        of = min(max(of, self.of_values[0]), self.of_values[-1])
        pressure = min(max(pressure, self.pressure_values[0]), self.pressure_values[-1])

        ideal_c_star = self._bilinear(self.fields["ideal_cstar_m_s"], of, pressure)
        molar_mass = self._bilinear(self.fields["effective_molar_mass_kg_mol"], of, pressure)
        return ThermochemicalState(
            of_ratio=of,
            chamber_pressure_pa=pressure,
            ideal_c_star_m_s=ideal_c_star,
            c_star_efficiency=efficiency,
            c_star_m_s=efficiency * ideal_c_star,
            gamma=self._bilinear(self.fields["gamma"], of, pressure),
            chamber_temperature_k=self._bilinear(
                self.fields["chamber_temperature_k"], of, pressure
            ),
            effective_molar_mass_kg_mol=molar_mass,
            gas_molar_mass_kg_mol=self._bilinear(
                self.fields["gas_molar_mass_kg_mol"], of, pressure
            ),
            # Recomputed rather than interpolated, so R = R_u / M holds exactly
            # everywhere and not merely at the grid nodes.
            specific_gas_constant_j_kg_k=_UNIVERSAL_GAS_CONSTANT_J_MOL_K / molar_mass,
            status=status,
        )

    # -- variants used only by the Milestone 5 sensitivity study ------------

    def subsample(self, *, of_stride: int = 1, pressure_stride: int = 1) -> ThermochemistryTable:
        """A coarser table built from every ``stride``-th node of this one.

        The coarse nodes are an exact subset of the committed CEA solutions and
        both endpoints are always kept, so the table spans the same rectangle.
        Any difference between the coarse and the full table is therefore pure
        *interpolation* error, with no change in the underlying chemistry -- which
        is what makes it a usable grid-convergence measure.
        """

        def indices(size: int, stride: int) -> np.ndarray:
            if stride < 1:
                raise ValueError(f"stride must be at least 1, got {stride!r}")
            kept = np.unique(np.concatenate([np.arange(0, size, stride), [size - 1]]))
            if kept.size < 2:
                raise ValueError(f"stride {stride!r} leaves fewer than two nodes")
            return kept

        rows = indices(self.of_values.size, of_stride)
        columns = indices(self.pressure_values.size, pressure_stride)
        return ThermochemistryTable(
            of_values=self.of_values[rows].copy(),
            pressure_values=self.pressure_values[columns].copy(),
            fields={name: grid[np.ix_(rows, columns)].copy() for name, grid in self.fields.items()},
            source=f"{self.source} (subsampled {of_stride}x{pressure_stride})",
        )

    def at_fixed_pressure(self, chamber_pressure_pa: float) -> ThermochemistryTable:
        """A table whose properties depend on O/F alone, frozen at one pressure.

        Every pressure column is replaced by the profile interpolated at
        ``chamber_pressure_pa``, so the pressure axis is retained (the chamber
        solver still sees the same valid rectangle) but carries no information.
        Comparing against the full table isolates how much the *pressure*
        dependence of the chemistry is worth, separately from the O/F dependence.
        """
        pressure = _check_finite_positive("chamber_pressure_pa", chamber_pressure_pa)
        low, high = self.pressure_bounds_pa
        if not (low <= pressure <= high):
            raise ValueError(
                f"chamber_pressure_pa {pressure!r} lies outside the tabulated span "
                f"[{low!r}, {high!r}] Pa"
            )
        fields = {}
        for name, grid in self.fields.items():
            profile = np.array([self._bilinear(grid, float(of), pressure) for of in self.of_values])
            fields[name] = np.repeat(profile[:, None], self.pressure_values.size, axis=1)
        return ThermochemistryTable(
            of_values=self.of_values.copy(),
            pressure_values=self.pressure_values.copy(),
            fields=fields,
            source=f"{self.source} (O/F only, frozen at {pressure / 1e5:.4g} bar)",
        )


@lru_cache(maxsize=4)
def default_table(path: str | None = None) -> ThermochemistryTable:
    """Load and cache the committed table (deterministic, read-only)."""
    return ThermochemistryTable.from_csv(DEFAULT_TABLE_PATH if path is None else Path(path))
