"""Independent verification of the nitrous oxide property module.

Independence strategy
---------------------
The reference values below were retrieved separately from the **NIST Chemistry
WebBook** saturation tabulation for nitrous oxide and are hard-coded here.  They
are *not* generated by this project's code.

An important honesty caveat, stated rather than glossed: NIST cites the same
equation of state that CoolProp uses for N2O (Lemmon & Span, J. Chem. Eng. Data
51 (2006) 785-850).  Agreement therefore verifies this module's **units, phase
selection and call structure** -- it does not independently validate the equation
of state itself.  That is exactly what a property-plumbing test should do.

A second, genuinely independent axis is checked as well: the low-level
``AbstractState`` interface used for speed must agree with CoolProp's
string-based ``PropsSI`` interface.
"""

from __future__ import annotations

import itertools
import math

import CoolProp.CoolProp as CP
import pytest

from hybrid_rocket_motor.nitrous_properties import (
    FLUID,
    MAX_VERIFIED_TEMPERATURE_K,
    MIN_VERIFIED_TEMPERATURE_K,
    PropertyRangeStatus,
    critical_pressure_pa,
    critical_temperature_k,
    isentropic_downstream_enthalpy_j_kg,
    property_range_status,
    saturated_liquid_density_kg_m3,
    saturated_liquid_enthalpy_j_kg,
    saturated_liquid_entropy_j_kg_k,
    saturated_liquid_internal_energy_j_kg,
    saturated_state,
    saturated_vapour_density_kg_m3,
    saturated_vapour_enthalpy_j_kg,
    saturated_vapour_internal_energy_j_kg,
    saturation_pressure_pa,
    triple_point_pressure_pa,
    triple_point_temperature_k,
)

#: NIST Chemistry WebBook saturation data for nitrous oxide, retrieved
#: independently of this project.  Columns: T [K], p [Pa], rho_l [kg/m^3],
#: rho_v [kg/m^3], h_l [kJ/kg], h_v [kJ/kg].
NIST_SATURATION_TABLE = (
    (200.0, 233674.0, 1184.37, 6.49348, 26.5016, 382.885),
    (205.0, 297673.0, 1168.83, 8.14596, 35.2350, 385.444),
    (210.0, 374307.0, 1152.98, 10.1044, 44.0248, 387.861),
    (215.0, 465092.0, 1136.81, 12.4070, 52.8810, 390.122),
    (220.0, 571598.0, 1120.27, 15.0954, 61.8141, 392.213),
    (225.0, 695440.0, 1103.34, 18.2157, 70.8357, 394.120),
    (230.0, 838278.0, 1085.96, 21.8193, 79.9579, 395.825),
    (235.0, 1001810.0, 1068.09, 25.9643, 89.1945, 397.310),
    (240.0, 1187770.0, 1049.67, 30.7169, 98.5605, 398.553),
    (245.0, 1397930.0, 1030.63, 36.1542, 108.073, 399.530),
    (250.0, 1634000.0, 1010.90, 42.367, 117.752, 400.211),
    (255.0, 1898000.0, 990.383, 49.464, 127.621, 400.561),
    (260.0, 2192000.0, 968.961, 57.580, 137.709, 400.538),
    (265.0, 2518000.0, 946.485, 66.880, 148.049, 400.087),
    (270.0, 2877000.0, 922.764, 77.583, 158.688, 399.140),
    (275.0, 3273000.0, 897.536, 89.975, 169.683, 397.604),
    (280.0, 3707000.0, 870.436, 104.458, 181.118, 395.355),
    (285.0, 4182000.0, 840.918, 121.618, 193.110, 392.206),
    (290.0, 4701000.0, 808.111, 142.379, 205.849, 387.870),
    (295.0, 5268000.0, 770.462, 168.359, 219.663, 381.848),
    (300.0, 5887000.0, 724.701, 202.906, 235.239, 373.119),
    (301.0, 6018140.0, 713.984, 211.442, 238.689, 370.868),
    (302.0, 6151290.0, 702.500, 220.765, 242.302, 368.376),
    (303.0, 6286960.0, 690.068, 231.058, 246.115, 365.590),
    (304.0, 6425260.0, 676.422, 242.582, 250.185, 362.431),
    (305.0, 6566310.0, 661.156, 255.742, 254.595, 358.785),
)


# --- 4. reference points against source data ------------------------------


@pytest.mark.parametrize(("temperature", "pressure", "rho_l", "rho_v", "h_l", "h_v"),
                         NIST_SATURATION_TABLE)
def test_saturation_properties_match_the_nist_tabulation(
    temperature, pressure, rho_l, rho_v, h_l, h_v
):
    """Tolerances are set by the WebBook's own 5-6 significant figures."""
    assert saturation_pressure_pa(temperature) == pytest.approx(pressure, rel=2.0e-4)
    assert saturated_liquid_density_kg_m3(temperature) == pytest.approx(rho_l, rel=2.0e-5)
    assert saturated_vapour_density_kg_m3(temperature) == pytest.approx(rho_v, rel=2.0e-5)
    assert saturated_liquid_enthalpy_j_kg(temperature) == pytest.approx(h_l * 1e3, rel=2.0e-5)
    assert saturated_vapour_enthalpy_j_kg(temperature) == pytest.approx(h_v * 1e3, rel=2.0e-5)


def test_room_temperature_vapour_pressure_matches_the_literature_value():
    """Waxman et al. quote ~730 psi (5.03 MPa) for N2O at room temperature."""
    assert saturation_pressure_pa(293.15) == pytest.approx(5.03e6, rel=0.01)


def test_low_level_and_string_interfaces_agree():
    """The AbstractState speed optimisation must not change any number."""
    for temperature in (210.0, 250.0, 293.15, 300.0):
        assert saturation_pressure_pa(temperature) == pytest.approx(
            CP.PropsSI("P", "T", temperature, "Q", 0, FLUID), rel=1e-12
        )
        assert saturated_liquid_density_kg_m3(temperature) == pytest.approx(
            CP.PropsSI("D", "T", temperature, "Q", 0, FLUID), rel=1e-12
        )
        assert saturated_vapour_density_kg_m3(temperature) == pytest.approx(
            CP.PropsSI("D", "T", temperature, "Q", 1, FLUID), rel=1e-12
        )
        assert saturated_liquid_internal_energy_j_kg(temperature) == pytest.approx(
            CP.PropsSI("U", "T", temperature, "Q", 0, FLUID), rel=1e-12
        )
        assert saturated_liquid_entropy_j_kg_k(temperature) == pytest.approx(
            CP.PropsSI("S", "T", temperature, "Q", 0, FLUID), rel=1e-12
        )


# --- 1, 2. saturation pressure --------------------------------------------


def test_saturation_pressure_is_positive_everywhere_in_range():
    for temperature, *_ in NIST_SATURATION_TABLE:
        assert saturation_pressure_pa(temperature) > 0.0


def test_saturation_pressure_increases_monotonically_with_temperature():
    pressures = [saturation_pressure_pa(t) for t, *_ in NIST_SATURATION_TABLE]
    assert all(later > earlier for earlier, later in itertools.pairwise(pressures))


def test_saturation_pressure_approaches_the_critical_pressure():
    near_critical = critical_temperature_k() - 0.01
    assert saturation_pressure_pa(near_critical) == pytest.approx(
        critical_pressure_pa(), rel=1e-3
    )


# --- 3. liquid denser than vapour -----------------------------------------


def test_liquid_is_denser_than_vapour_throughout_the_two_phase_domain():
    for temperature, *_ in NIST_SATURATION_TABLE:
        assert saturated_liquid_density_kg_m3(temperature) > saturated_vapour_density_kg_m3(
            temperature
        )


def test_liquid_density_falls_and_vapour_density_rises_with_temperature():
    liquid = [saturated_liquid_density_kg_m3(t) for t, *_ in NIST_SATURATION_TABLE]
    vapour = [saturated_vapour_density_kg_m3(t) for t, *_ in NIST_SATURATION_TABLE]
    assert all(later < earlier for earlier, later in itertools.pairwise(liquid))
    assert all(later > earlier for earlier, later in itertools.pairwise(vapour))


def test_latent_heat_is_positive_and_shrinks_towards_the_critical_point():
    latents = [saturated_state(t).latent_heat_j_kg for t, *_ in NIST_SATURATION_TABLE]
    assert all(value > 0.0 for value in latents)
    assert all(later < earlier for earlier, later in itertools.pairwise(latents))


def test_latent_heat_matches_the_nist_enthalpy_difference():
    for temperature, _p, _rl, _rv, h_l, h_v in NIST_SATURATION_TABLE:
        assert saturated_state(temperature).latent_heat_j_kg == pytest.approx(
            (h_v - h_l) * 1e3, rel=1e-4
        )


def test_internal_energy_is_below_enthalpy_for_both_phases():
    """u = h - p/rho, so u < h wherever p and rho are positive."""
    for temperature, *_ in NIST_SATURATION_TABLE:
        state = saturated_state(temperature)
        assert state.liquid_internal_energy_j_kg < state.liquid_enthalpy_j_kg
        assert state.vapour_internal_energy_j_kg < state.vapour_enthalpy_j_kg
        assert state.liquid_internal_energy_j_kg == pytest.approx(
            state.liquid_enthalpy_j_kg - state.pressure_pa / state.liquid_density_kg_m3,
            rel=1e-9,
        )
        assert state.vapour_internal_energy_j_kg == pytest.approx(
            state.vapour_enthalpy_j_kg - state.pressure_pa / state.vapour_density_kg_m3,
            rel=1e-9,
        )


# --- 5, 6. range and critical-point guards --------------------------------


def test_critical_and_triple_point_values():
    assert critical_temperature_k() == pytest.approx(309.52, rel=1e-4)
    assert critical_pressure_pa() == pytest.approx(7.2448e6, rel=1e-4)
    assert triple_point_temperature_k() == pytest.approx(182.33, rel=1e-4)
    assert triple_point_pressure_pa() == pytest.approx(87837.0, rel=1e-4)


def test_range_status_classification():
    assert property_range_status(250.0) is PropertyRangeStatus.VERIFIED
    assert property_range_status(MIN_VERIFIED_TEMPERATURE_K) is PropertyRangeStatus.VERIFIED
    assert property_range_status(MAX_VERIFIED_TEMPERATURE_K) is PropertyRangeStatus.VERIFIED
    assert property_range_status(190.0) is PropertyRangeStatus.BELOW_VERIFIED_RANGE
    assert property_range_status(307.0) is PropertyRangeStatus.ABOVE_VERIFIED_RANGE


def test_evaluation_outside_the_checked_band_is_flagged_not_silent():
    """Still evaluable -- the EOS is valid -- but never silently."""
    state = saturated_state(307.0)
    assert state.pressure_pa > 0.0
    assert not state.is_within_verified_range
    assert state.range_status is PropertyRangeStatus.ABOVE_VERIFIED_RANGE


@pytest.mark.parametrize("bad", [309.5207, 310.0, 400.0])
def test_at_or_above_the_critical_point_is_rejected(bad):
    with pytest.raises(ValueError, match="critical"):
        saturation_pressure_pa(bad)


@pytest.mark.parametrize("bad", [182.33, 180.0, 100.0, 0.0, -5.0])
def test_at_or_below_the_triple_point_is_rejected(bad):
    with pytest.raises(ValueError, match="triple"):
        saturation_pressure_pa(bad)


# --- 7. finite-input rejection --------------------------------------------


@pytest.mark.parametrize("bad", [math.nan, math.inf, -math.inf])
def test_non_finite_temperature_is_rejected_by_every_property(bad):
    for getter in (
        saturation_pressure_pa,
        saturated_liquid_density_kg_m3,
        saturated_vapour_density_kg_m3,
        saturated_liquid_enthalpy_j_kg,
        saturated_vapour_enthalpy_j_kg,
        saturated_liquid_internal_energy_j_kg,
        saturated_vapour_internal_energy_j_kg,
        saturated_liquid_entropy_j_kg_k,
        saturated_state,
        property_range_status,
    ):
        with pytest.raises(ValueError):
            getter(bad)


@pytest.mark.parametrize("bad_pressure", [0.0, -1.0e5, math.nan, math.inf])
def test_isentropic_expansion_rejects_invalid_downstream_pressure(bad_pressure):
    s1 = saturated_liquid_entropy_j_kg_k(293.15)
    with pytest.raises(ValueError):
        isentropic_downstream_enthalpy_j_kg(s1, bad_pressure)


def test_isentropic_expansion_rejects_non_finite_entropy():
    with pytest.raises(ValueError):
        isentropic_downstream_enthalpy_j_kg(math.nan, 2.0e6)


# --- isentropic expansion behaviour ---------------------------------------


def test_isentropic_expansion_lowers_enthalpy_and_density():
    state = saturated_state(293.15)
    h2, rho2 = isentropic_downstream_enthalpy_j_kg(
        state.liquid_entropy_j_kg_k, 0.5 * state.pressure_pa
    )
    assert h2 < state.liquid_enthalpy_j_kg
    assert rho2 < state.liquid_density_kg_m3
    assert h2 > 0.0
    assert rho2 > 0.0


def test_isentropic_expansion_to_the_saturation_pressure_recovers_the_liquid_state():
    """Expanding to the pressure it is already at must change nothing."""
    state = saturated_state(280.0)
    h2, rho2 = isentropic_downstream_enthalpy_j_kg(
        state.liquid_entropy_j_kg_k, state.pressure_pa
    )
    assert h2 == pytest.approx(state.liquid_enthalpy_j_kg, rel=1e-6)
    assert rho2 == pytest.approx(state.liquid_density_kg_m3, rel=1e-6)


def test_deeper_expansion_lowers_enthalpy_further():
    state = saturated_state(293.15)
    enthalpies = [
        isentropic_downstream_enthalpy_j_kg(state.liquid_entropy_j_kg_k, p)[0]
        for p in (4.0e6, 3.0e6, 2.0e6, 1.0e6)
    ]
    assert all(later < earlier for earlier, later in itertools.pairwise(enthalpies))


def test_saturated_state_bundles_agree_with_the_individual_getters():
    for temperature in (215.0, 260.0, 293.15):
        state = saturated_state(temperature)
        assert state.pressure_pa == saturation_pressure_pa(temperature)
        assert state.liquid_density_kg_m3 == saturated_liquid_density_kg_m3(temperature)
        assert state.vapour_density_kg_m3 == saturated_vapour_density_kg_m3(temperature)
        assert state.liquid_enthalpy_j_kg == saturated_liquid_enthalpy_j_kg(temperature)
        assert state.vapour_enthalpy_j_kg == saturated_vapour_enthalpy_j_kg(temperature)
        assert state.liquid_internal_energy_j_kg == saturated_liquid_internal_energy_j_kg(
            temperature
        )
        assert state.liquid_entropy_j_kg_k == saturated_liquid_entropy_j_kg_k(temperature)


def test_saturation_state_is_immutable():
    with pytest.raises(Exception):  # noqa: B017 - dataclass raises FrozenInstanceError
        saturated_state(280.0).pressure_pa = 1.0
